### ISSUE TITLE
SAM validation error

### ISSUE THREAD

**Issue by luhuifang** [WGLab/HadoopCNV#4]
Hi,
I try to run software using example dataset, but there is one error :

Error: htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 4360, Read name ERR003981.11622682, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:454)

Can you explain the reason of this error?

**Comment by kaichop** [comment]
this is an exception from  htsjdk.samtools. You should contact them to
solve it.

**Comment by luhuifang** [comment]
I have been running successfully, thanks!
